// <auto-generated />
using System;
using API_Copa_do_Mundo_2022.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API_Copa_do_Mundo_2022.Migrations
{
    [DbContext(typeof(DbContexto))]
    partial class DbContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("API_Copa_do_Mundo_2022.Models.Administrador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("nome");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("senha");

                    b.HasKey("Id");

                    b.ToTable("administradores");
                });

            modelBuilder.Entity("API_Copa_do_Mundo_2022.Models.Clube", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Descricao")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("descricao");

                    b.Property<int>("GruposId")
                        .HasColumnType("int")
                        .HasColumnName("grupos_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("nome");

                    b.Property<string>("UrlBandeira")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("url_bandeira");

                    b.HasKey("Id");

                    b.HasIndex("GruposId");

                    b.ToTable("clubes");
                });

            modelBuilder.Entity("API_Copa_do_Mundo_2022.Models.Estatistica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int?>("CartoesAmarelos")
                        .HasColumnType("int")
                        .HasColumnName("cartoes_amarelos");

                    b.Property<int?>("CartoesVermelhos")
                        .HasColumnType("int")
                        .HasColumnName("cartoes_vermelhos");

                    b.Property<int?>("Chutes")
                        .HasColumnType("int")
                        .HasColumnName("chutes");

                    b.Property<int?>("ChutesAGol")
                        .HasColumnType("int")
                        .HasColumnName("chutes_a_gol");

                    b.Property<int>("ClubesId")
                        .HasColumnType("int")
                        .HasColumnName("clubes_id");

                    b.Property<int?>("Escanteios")
                        .HasColumnType("int")
                        .HasColumnName("escanteios");

                    b.Property<int?>("Faltas")
                        .HasColumnType("int")
                        .HasColumnName("faltas");

                    b.Property<int?>("Impedimentos")
                        .HasColumnType("int")
                        .HasColumnName("impedimentos");

                    b.Property<int>("PartidaId")
                        .HasColumnType("int")
                        .HasColumnName("partidas_id");

                    b.Property<int?>("Passes")
                        .HasColumnType("int")
                        .HasColumnName("passes");

                    b.Property<int?>("PosseDeBola")
                        .HasColumnType("int")
                        .HasColumnName("posse_de_bola");

                    b.Property<int?>("PrecisaoDePasses")
                        .HasColumnType("int")
                        .HasColumnName("precisao_de_passes");

                    b.HasKey("Id");

                    b.HasIndex("ClubesId");

                    b.HasIndex("PartidaId");

                    b.ToTable("estatisticas");
                });

            modelBuilder.Entity("API_Copa_do_Mundo_2022.Models.Fase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("fases");
                });

            modelBuilder.Entity("API_Copa_do_Mundo_2022.Models.Grupo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("grupos");
                });

            modelBuilder.Entity("API_Copa_do_Mundo_2022.Models.Partida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_hora");

                    b.Property<int>("FasesId")
                        .HasColumnType("int")
                        .HasColumnName("fases_id");

                    b.Property<byte?>("Finalizado")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("finalizado");

                    b.Property<byte?>("Iniciado")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("iniciado");

                    b.HasKey("Id");

                    b.HasIndex("FasesId");

                    b.ToTable("partidas");
                });

            modelBuilder.Entity("API_Copa_do_Mundo_2022.Models.PartidaClube", b =>
                {
                    b.Property<int>("PartidaId")
                        .HasColumnType("int")
                        .HasColumnName("partidas_id");

                    b.Property<int>("ClubeIdA")
                        .HasColumnType("int")
                        .HasColumnName("clubes_id_a");

                    b.Property<int>("ClubeIdB")
                        .HasColumnType("int")
                        .HasColumnName("clubes_id_b");

                    b.HasKey("PartidaId", "ClubeIdA", "ClubeIdB");

                    b.HasIndex("ClubeIdA");

                    b.HasIndex("ClubeIdB");

                    b.HasIndex("PartidaId")
                        .IsUnique();

                    b.ToTable("partidas_clubes");
                });

            modelBuilder.Entity("API_Copa_do_Mundo_2022.Models.Clube", b =>
                {
                    b.HasOne("API_Copa_do_Mundo_2022.Models.Grupo", "Grupo")
                        .WithMany()
                        .HasForeignKey("GruposId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("API_Copa_do_Mundo_2022.Models.Estatistica", b =>
                {
                    b.HasOne("API_Copa_do_Mundo_2022.Models.Clube", "Clube")
                        .WithMany()
                        .HasForeignKey("ClubesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_Copa_do_Mundo_2022.Models.Partida", "Partida")
                        .WithMany()
                        .HasForeignKey("PartidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clube");

                    b.Navigation("Partida");
                });

            modelBuilder.Entity("API_Copa_do_Mundo_2022.Models.Partida", b =>
                {
                    b.HasOne("API_Copa_do_Mundo_2022.Models.Fase", "Fase")
                        .WithMany()
                        .HasForeignKey("FasesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fase");
                });

            modelBuilder.Entity("API_Copa_do_Mundo_2022.Models.PartidaClube", b =>
                {
                    b.HasOne("API_Copa_do_Mundo_2022.Models.Clube", "ClubeA")
                        .WithMany("PartidasClubesA")
                        .HasForeignKey("ClubeIdA")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_Copa_do_Mundo_2022.Models.Clube", "ClubeB")
                        .WithMany("PartidasClubesB")
                        .HasForeignKey("ClubeIdB")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_Copa_do_Mundo_2022.Models.Partida", "Partida")
                        .WithMany("PartidasClubes")
                        .HasForeignKey("PartidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClubeA");

                    b.Navigation("ClubeB");

                    b.Navigation("Partida");
                });

            modelBuilder.Entity("API_Copa_do_Mundo_2022.Models.Clube", b =>
                {
                    b.Navigation("PartidasClubesA");

                    b.Navigation("PartidasClubesB");
                });

            modelBuilder.Entity("API_Copa_do_Mundo_2022.Models.Partida", b =>
                {
                    b.Navigation("PartidasClubes");
                });
#pragma warning restore 612, 618
        }
    }
}
